export const ALPHABET_FLAGS = [
  {
    key: "alpha",
    name: "Alpha",
    type: "flag-letter",
    category: "letters",
    meaning: "Divers or friendly EOD personnel down.",
    description: "Vertical white and blue connection.",
    phonetic: "Al-fah",
    tips: "Looks like a diver's fin or a swallow tail cut (though it is rectangular). Memorize: A-lpha = A-ngle (the diagonal cut).",
    colors: ["white", "blue"],
    pattern: "vertical-bicolor",
    imagePath: "/flags/flag-letters/alpha.svg",
    difficulty: "beginner",
    order: 1
  },
  {
    key: "bravo",
    name: "Bravo",
    type: "flag-letter",
    category: "letters",
    meaning: "Weapon Practices, Fueling or Transferring Explosives.",
    description: "Solid red flag with a swallow tail.",
    phonetic: "Brah-voh",
    tips: "B = Blood red. Or 'Boom' (dangerous cargo).",
    colors: ["red"],
    pattern: "solid",
    imagePath: "/flags/flag-letters/bravo.svg",
    difficulty: "beginner",
    order: 2
  },
  {
    key: "charlie",
    name: "Charlie",
    type: "flag-letter",
    category: "letters",
    meaning: "Affirmative.",
    description: "Horizontal stripes: Blue, White, Red, White, Blue.",
    phonetic: "Char-lee",
    tips: "C = Colorful (5 stripes).",
    colors: ["blue", "white", "red"],
    pattern: "horizontal-stripes",
    imagePath: "/flags/flag-letters/charlie.svg",
    difficulty: "intermediate",
    order: 3
  },
  {
    key: "delta",
    name: "Delta",
    type: "flag-letter",
    category: "letters",
    meaning: "Degaussing.",
    description: "Yellow, Blue, Yellow horizontal bands.",
    phonetic: "Dell-tah",
    tips: "D = Divider (blue divides the yellow).",
    colors: ["yellow", "blue"],
    pattern: "horizontal-stripes",
    imagePath: "/flags/flag-letters/delta.svg",
    difficulty: "intermediate",
    order: 4
  },
  {
    key: "echo",
    name: "Echo",
    type: "flag-letter",
    category: "letters",
    meaning: "No RF Danger.",
    description: "Blue on top, Red on bottom.",
    phonetic: "Eck-oh",
    tips: "E = Earth (red) below Sky (blue). Or 'Equator' dividing the two.",
    colors: ["blue", "red"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/flag-letters/echo.svg",
    difficulty: "beginner",
    order: 5
  },
  {
    key: "foxtrot",
    name: "Foxtrot",
    type: "flag-letter",
    category: "letters",
    meaning: "Flight Operations.",
    description: "White with a red diamond.",
    phonetic: "Foks-trot",
    tips: "F = Four corners of the diamond. Or 'Fox' in the hole (diamond).",
    colors: ["white", "red"],
    pattern: "diamond",
    imagePath: "/flags/flag-letters/foxtrot.svg",
    difficulty: "advanced",
    order: 6
  },
  {
    key: "golf",
    name: "Golf",
    type: "flag-letter",
    category: "letters",
    meaning: "I am Guide Ship.",
    description: "Vertical stripes: Yellow, Blue, Yellow, Blue, Yellow, Blue.",
    phonetic: "Golf",
    tips: "G = Gridiron (looks like stripes on a field).",
    colors: ["yellow", "blue"],
    pattern: "vertical-stripes",
    imagePath: "/flags/flag-letters/golf.svg",
    difficulty: "intermediate",
    order: 7
  },
  {
    key: "hotel",
    name: "Hotel",
    type: "flag-letter",
    category: "letters",
    meaning: "Helicopter Operations.",
    description: "White on left, Red on right.",
    phonetic: "Hoh-tel",
    tips: "H = Half. Half white, half red.",
    colors: ["white", "red"],
    pattern: "vertical-bicolor",
    imagePath: "/flags/flag-letters/hotel.svg",
    difficulty: "beginner",
    order: 8
  },
  {
    key: "india",
    name: "India",
    type: "flag-letter",
    category: "letters",
    meaning: "Going Alongside.",
    description: "Yellow background with a black circle.",
    phonetic: "In-dee-ah",
    tips: "I = Island (black circle) in the sun (yellow).",
    colors: ["yellow", "black"],
    pattern: "circle",
    imagePath: "/flags/flag-letters/india.svg",
    difficulty: "beginner",
    order: 9
  },
  {
    key: "juliett",
    name: "Juliett",
    type: "flag-letter",
    category: "letters",
    meaning: "Spare.",
    description: "Blue, White, Blue horizontal stripes.",
    phonetic: "Jew-lee-ett",
    tips: "J = Jelly sandwich (white filling). Same as Charlie but fewer stripes.",
    colors: ["blue", "white"],
    pattern: "horizontal-stripes",
    imagePath: "/flags/flag-letters/juliet.svg",
    difficulty: "intermediate",
    order: 10
  },
  {
    key: "kilo",
    name: "Kilo",
    type: "flag-letter",
    category: "letters",
    meaning: "Personnel Working Aloft and/or Over the Side.",
    description: "Yellow on left, Blue on right.",
    phonetic: "Key-loh",
    tips: "K = Kickoff. Similar to Hotel but Yellow/Blue.",
    colors: ["yellow", "blue"],
    pattern: "vertical-bicolor",
    imagePath: "/flags/flag-letters/kilo.svg",
    difficulty: "intermediate",
    order: 11
  },
  {
    key: "lima",
    name: "Lima",
    type: "flag-letter",
    category: "letters",
    meaning: "RADHAZ/HERO Warning.",
    description: "Quartered: Yellow (top-left/bottom-right) and Black (top-right/bottom-left).",
    phonetic: "Lee-mah",
    tips: "L = Laboratory warning (yellow/black warning/hazard colors).",
    colors: ["yellow", "black"],
    pattern: "quarters",
    imagePath: "/flags/flag-letters/lima.svg",
    difficulty: "intermediate",
    order: 12
  },
  {
    key: "mike",
    name: "Mike",
    type: "flag-letter",
    category: "letters",
    meaning: "Medical Duty Ship.",
    description: "Blue with a white X (saltire).",
    phonetic: "Mike",
    tips: "M = Medical (Scottish cross pattern/details). Looks like an 'X' for 'Marks the spot'.",
    colors: ["blue", "white"],
    pattern: "saltire",
    imagePath: "/flags/flag-letters/mike.svg",
    difficulty: "advanced",
    order: 13
  },
  {
    key: "november",
    name: "November",
    type: "flag-letter",
    category: "letters",
    meaning: "Your Movements Not Understood.",
    description: "Checkered blue and white (4x4 grid).",
    phonetic: "No-vem-ber",
    tips: "N = No. Checkered flag like finish line, but blue/white squares.",
    colors: ["blue", "white"],
    pattern: "checkered",
    imagePath: "/flags/flag-letters/november.svg",
    difficulty: "advanced",
    order: 14
  },
  {
    key: "oscar",
    name: "Oscar",
    type: "flag-letter",
    category: "letters",
    meaning: "Person Overboard.",
    description: "Diagonally split: Red (top-left) and Yellow (bottom-right).",
    phonetic: "Oss-cah",
    tips: "O = Overboard. Red over Yellow.",
    colors: ["red", "yellow"],
    pattern: "diagonal-split",
    imagePath: "/flags/flag-letters/oscar.svg",
    difficulty: "intermediate",
    order: 15
  },
  {
    key: "papa",
    name: "Papa",
    type: "flag-letter",
    category: "letters",
    meaning: "General Recall.",
    description: "Blue square with a white central square.",
    phonetic: "Pah-pah",
    tips: "P = Peer inside (white center). 'Blue Peter'.",
    colors: ["blue", "white"],
    pattern: "square",
    imagePath: "/flags/flag-letters/papa.svg",
    difficulty: "intermediate",
    order: 16
  },
  {
    key: "quebec",
    name: "Quebec",
    type: "flag-letter",
    category: "letters",
    meaning: "Boat Recall.",
    description: "Solid yellow.",
    phonetic: "Keh-beck",
    tips: "Q = Quarantine. Yellow is the traditional color of quarantine/sickness warning, but here it requests clearance.",
    colors: ["yellow"],
    pattern: "solid",
    imagePath: "/flags/flag-letters/quebec.svg",
    difficulty: "beginner",
    order: 17
  },
  {
    key: "romeo",
    name: "Romeo",
    type: "flag-letter",
    category: "letters",
    meaning: "Ready Duty Ship",
    description: "Red with a yellow cross.",
    phonetic: "Row-me-oh",
    tips: "R = Red Cross (though yellow here). 'Roger' in voice, but Romeo in flags.",
    colors: ["red", "yellow"],
    pattern: "cross",
    imagePath: "/flags/flag-letters/romeo.svg",
    difficulty: "intermediate",
    order: 18
  },
  {
    key: "sierra",
    name: "Sierra",
    type: "flag-letter",
    category: "letters",
    meaning: "Drill Signal.",
    description: "White with a blue central square.",
    phonetic: "See-air-rah",
    tips: "S = Square (opposite of Papa). White outer, Blue inner.",
    colors: ["white", "blue"],
    pattern: "square",
    imagePath: "/flags/flag-letters/sierra.svg",
    difficulty: "intermediate",
    order: 19
  },
  {
    key: "tango",
    name: "Tango",
    type: "flag-letter",
    category: "letters",
    meaning: "Time Indicator.",
    description: "Vertical stripes: Red, White, Blue.",
    phonetic: "Tang-go",
    tips: "T = Tricolor (like the French flag).",
    colors: ["red", "white", "blue"],
    pattern: "vertical-stripes",
    imagePath: "/flags/flag-letters/tango.svg",
    difficulty: "intermediate",
    order: 20
  },
  {
    key: "uniform",
    name: "Uniform",
    type: "flag-letter",
    category: "letters",
    meaning: "Anchoring, Mooring, Weighing.",
    description: "Quartered: Red (top-left/bottom-right) and White (top-right/bottom-left).",
    phonetic: "You-nee-form",
    tips: "U = Uh oh (danger). Red and white checks.",
    colors: ["red", "white"],
    pattern: "quarters",
    imagePath: "/flags/flag-letters/uniform.svg",
    difficulty: "intermediate",
    order: 21
  },
  {
    key: "victor",
    name: "Victor",
    type: "flag-letter",
    category: "letters",
    meaning: "Streaming/Recovering Towed Acoustic Devices.",
    description: "White with a red X (saltire).",
    phonetic: "Vik-tah",
    tips: "V = Very needing help. Red X on white.",
    colors: ["white", "red"],
    pattern: "saltire",
    imagePath: "/flags/flag-letters/victor.svg",
    difficulty: "beginner",
    order: 22
  },
  {
    key: "whiskey",
    name: "Whiskey",
    type: "flag-letter",
    category: "letters",
    meaning: "Information Addressee.",
    description: "Concentric squares: Blue (outer), White, Red (inner).",
    phonetic: "Wiss-key",
    tips: "W = With another color inside (3 colors).",
    colors: ["blue", "white", "red"],
    pattern: "concentric-squares",
    imagePath: "/flags/flag-letters/whiskey.svg",
    difficulty: "advanced",
    order: 23
  },
  {
    key: "xray",
    name: "X-ray",
    type: "flag-letter",
    category: "letters",
    meaning: "Evolution or Exercise Completed.",
    description: "White with a blue cross.",
    phonetic: "Ecks-ray",
    tips: "X = Cross. Blue cross on white.",
    colors: ["white", "blue"],
    pattern: "cross",
    imagePath: "/flags/flag-letters/xray.svg",
    difficulty: "intermediate",
    order: 24
  },
  {
    key: "yankee",
    name: "Yankee",
    type: "flag-letter",
    category: "letters",
    meaning: "Acknowledge.",
    description: "Diagonal stripes: Yellow and Red.",
    phonetic: "Yang-key",
    tips: "Y = Yellow/Red diagonal stripes.",
    colors: ["yellow", "red"],
    pattern: "diagonal-stripes",
    imagePath: "/flags/flag-letters/yankee.svg",
    difficulty: "advanced",
    order: 25
  },
  {
    key: "zulu",
    name: "Zulu",
    type: "flag-letter",
    category: "letters",
    meaning: "Communication Guard.",
    description: "Diagonally divided: Yellow, Black, Red, Blue (triangles).",
    phonetic: "Zoo-loo",
    tips: "Z = Zigzag (the diagonal cuts look chaotic). Black/Red/Blue/Yellow.",
    colors: ["yellow", "black", "red", "blue"],
    pattern: "diagonal-quarters",
    imagePath: "/flags/flag-letters/zulu.svg",
    difficulty: "advanced",
    order: 26
  }
];
