export const NUMBER_FLAGS = [
  {
    key: "zero",
    name: "Zero",
    type: "flag-number",
    category: "numbers",
    meaning: "Military Guard",
    description: "Yellow, Red, Yellow, Red, Yellow vertical stripes.",
    phonetic: "Zee-ro",
    tips: "Five vertical stripes (Y-R-Y-R-Y).",
    colors: ["yellow", "red"],
    pattern: "vertical-stripes",
    imagePath: "/flags/flag-numbers/zero.svg",
    difficulty: "beginner",
    order: 0
  },
  {
    key: "one",
    name: "One",
    type: "flag-number",
    category: "numbers",
    meaning: "Anti-Submarine Warfare Action Table",
    description: "White with a red horizontal stripe.",
    phonetic: "Wun",
    tips: "One stripe (red). Looks like the Japanese flag but with a stripe/circle?",
    colors: ["white", "red"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/flag-numbers/one.svg",
    difficulty: "beginner",
    order: 1
  },
  {
    key: "two",
    name: "Two",
    type: "flag-number",
    category: "numbers",
    meaning: "Surface Action Table.",
    description: "Blue with a white circle.",
    phonetic: "Too",
    tips: "Blue background, white circle (like a target).",
    colors: ["blue", "white"],
    pattern: "circle",
    imagePath: "/flags/flag-numbers/two.svg",
    difficulty: "beginner",
    order: 2
  },
  {
    key: "three",
    name: "Three",
    type: "flag-number",
    category: "numbers",
    meaning: "Surface Action Table - Over-the-Horizon Engagement.",
    description: "Vertical stripes: Red, White, Blue.",
    phonetic: "Tree",
    tips: "Three colors (Red, White, Blue). Same as Tango.",
    colors: ["red", "white", "blue"],
    pattern: "vertical-stripes",
    imagePath: "/flags/flag-numbers/three.svg",
    difficulty: "intermediate",
    order: 3
  },
  {
    key: "four",
    name: "Four",
    type: "flag-number",
    category: "numbers",
    meaning: "Surface Action Table - To-the-Horizon Range Engagement.",
    description: "Red with a white cross.",
    phonetic: "Fower",
    tips: "Four arms of the cross. Denmark flag.",
    colors: ["red", "white"],
    pattern: "cross",
    imagePath: "/flags/flag-numbers/four.svg",
    difficulty: "beginner",
    order: 4
  },
  {
    key: "five",
    name: "Five",
    type: "flag-number",
    category: "numbers",
    meaning: "Breakdown.",
    description: "Vertical stripes: Yellow, Blue.",
    phonetic: "Fife",
    tips: "Five fingers, two colors (Yellow/Blue). Same as Kilo?",
    colors: ["yellow", "blue"],
    pattern: "vertical-bicolor",
    imagePath: "/flags/flag-numbers/five.svg",
    difficulty: "intermediate",
    order: 5
  },
  {
    key: "six",
    name: "Six",
    type: "flag-number",
    category: "numbers",
    meaning: "Towing Operations.",
    description: "Horizontally divided: Black over White.",
    phonetic: "Siks",
    tips: "Top half black, bottom half white.",
    colors: ["black", "white"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/flag-numbers/six.svg",
    difficulty: "intermediate",
    order: 6
  },
  {
    key: "seven",
    name: "Seven",
    type: "flag-number",
    category: "numbers",
    meaning: "Anti-Air Warfare Action Table.",
    description: "Horizontally divided: Yellow over Red.",
    phonetic: "Sev-en",
    tips: "Yellow over Red. (Similar to Oscar but horizontal).",
    colors: ["yellow", "red"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/flag-numbers/seven.svg",
    difficulty: "intermediate",
    order: 7
  },
  {
    key: "eight",
    name: "Eight",
    type: "flag-number",
    category: "numbers",
    meaning: "Boat Signal.",
    description: "White with a red cross (saltire).",
    phonetic: "Ait",
    tips: "Same as Victor (Red X on white).",
    colors: ["white", "red"],
    pattern: "saltire",
    imagePath: "/flags/flag-numbers/eight.svg",
    difficulty: "intermediate",
    order: 8
  },
  {
    key: "nine",
    name: "Nine",
    type: "flag-number",
    category: "numbers",
    meaning: "Torpedo Action Table.",
    description: "Quartered: White (top-left/bottom-right) and Black (top-right/bottom-left).",
    phonetic: "Nin-er",
    tips: "Opposite of Lima? Or similar pattern.",
    colors: ["white", "black"],
    pattern: "quarters",
    imagePath: "/flags/flag-numbers/nine.svg",
    difficulty: "intermediate",
    order: 9
  }
];

export const PENNANT_NUMBERS = [
  {
    key: "p1",
    name: "Pennant One",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 1.",
    description: "White with a red disc.",
    phonetic: "Wun",
    tips: "Japanese flag on a pennant.",
    colors: ["white", "red"],
    pattern: "circle",
    imagePath: "/flags/pennant-numbers/p1.svg",
    difficulty: "beginner",
    order: 1
  },
  {
    key: "p2",
    name: "Pennant Two",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 2.",
    description: "Blue with a white disc.",
    phonetic: "Too",
    tips: "Blue pennant, white circle.",
    colors: ["blue", "white"],
    pattern: "circle",
    imagePath: "/flags/pennant-numbers/p2.svg",
    difficulty: "beginner",
    order: 2
  },
  {
    key: "p3",
    name: "Pennant Three",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 3.",
    description: "Vertical stripes: Red, White, Blue.",
    phonetic: "Tree",
    tips: "French flag on a pennant.",
    colors: ["red", "white", "blue"],
    pattern: "vertical-stripes",
    imagePath: "/flags/pennant-numbers/p3.svg",
    difficulty: "intermediate",
    order: 3
  },
  {
    key: "p4",
    name: "Pennant Four",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 4.",
    description: "Red with a white cross.",
    phonetic: "Fower",
    tips: "Danish flag on a pennant.",
    colors: ["red", "white"],
    pattern: "cross",
    imagePath: "/flags/pennant-numbers/p4.svg",
    difficulty: "beginner",
    order: 4
  },
  {
    key: "p5",
    name: "Pennant Five",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 5.",
    description: "Vertical stripes: Yellow and Blue.",
    phonetic: "Fife",
    tips: "Left yellow, right blue.",
    colors: ["yellow", "blue"],
    pattern: "vertical-bicolor",
    imagePath: "/flags/pennant-numbers/p5.svg",
    difficulty: "intermediate",
    order: 5
  },
  {
    key: "p6",
    name: "Pennant Six",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 6.",
    description: "Horizontally divided: Black over White.",
    phonetic: "Siks",
    tips: "Top black, bottom white.",
    colors: ["black", "white"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/pennant-numbers/p6.svg",
    difficulty: "intermediate",
    order: 6
  },
  {
    key: "p7",
    name: "Pennant Seven",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 7.",
    description: "Horizontally divided: Yellow over Red.",
    phonetic: "Sev-en",
    tips: "Top yellow, bottom red.",
    colors: ["yellow", "red"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/pennant-numbers/p7.svg",
    difficulty: "intermediate",
    order: 7
  },
  {
    key: "p8",
    name: "Pennant Eight",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 8.",
    description: "White with a red cross.",
    phonetic: "Ait",
    tips: "Red cross on white (like St George's cross).",
    colors: ["white", "red"],
    pattern: "cross",
    imagePath: "/flags/pennant-numbers/p8.svg",
    difficulty: "intermediate",
    order: 8
  },
  {
    key: "p9",
    name: "Pennant Nine",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 9.",
    description: "Quartered: White and Black.",
    phonetic: "Nin-er",
    tips: "Checkered white and black.",
    colors: ["white", "black"],
    pattern: "quarters",
    imagePath: "/flags/pennant-numbers/p9.svg",
    difficulty: "intermediate",
    order: 9
  },
  {
    key: "p0",
    name: "Pennant Zero",
    type: "pennant-number",
    category: "numbers",
    meaning: "Pennant 0.",
    description: "Vertical stripes: Yellow, Red, Yellow.",
    phonetic: "Zee-ro",
    tips: "Yellow, Red, Yellow stripes.",
    colors: ["yellow", "red"],
    pattern: "vertical-stripes",
    imagePath: "/flags/pennant-numbers/p0.svg",
    difficulty: "intermediate",
    order: 0
  }
];
