import { Doc } from "../../convex/_generated/dataModel";

export const SPECIAL_PENNANTS: Omit<Doc<"flags">, "_id" | "_creationTime">[] = [
  {
    key: "answering",
    name: "Answering Pennant",
    type: "special-pennant",
    category: "special",
    meaning: "Acknowledgement / Code Flag.",
    description: "Vertical stripes: Red, White, Red, White, Red.",
    phonetic: "An-ser-ing",
    tips: "Candy cane stripes (red/white).",
    colors: ["red", "white"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/answer.svg",
    difficulty: "beginner",
    order: 1
  },
  {
    key: "code",
    name: "Code Flag",
    type: "special-pennant",
    category: "special",
    meaning: "Use International Code of Signals.",
    description: "Vertical stripes: Red, White, Red, White, Red (Same as Answering).",
    phonetic: "Code",
    tips: "Same as Answering Pennant.",
    colors: ["red", "white"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/answer.svg",
    difficulty: "beginner",
    order: 2
  },
  {
    key: "corpen",
    name: "Corpen",
    type: "special-pennant",
    category: "special",
    meaning: "Course Pennant - Stop the turn.",
    description: "Pennant with red and white vertical stripes.",
    phonetic: "Cor-pen",
    tips: "Red and white vertical stripes.",
    colors: ["red", "white"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/corpen.svg",
    difficulty: "advanced",
    order: 3
  },
  {
    key: "designation",
    name: "Designation",
    type: "special-pennant",
    category: "special",
    meaning: "Plain Text.",
    description: "Pennant with white and black vertical stripes.",
    phonetic: "Desig-nay-shun",
    tips: "White and black vertical stripes.",
    colors: ["white", "black"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/desig.svg",
    difficulty: "advanced",
    order: 4
  },
  {
    key: "division",
    name: "Division",
    type: "special-pennant",
    category: "special",
    meaning: "Division.",
    description: "Pennant with red, white, red vertical bands.",
    phonetic: "Di-vi-sion",
    tips: "Typically red, white, red.",
    colors: ["red", "white"],
    pattern: "vertical-bicolor",
    imagePath: "/flags/special-pennants/division.svg",
    difficulty: "advanced",
    order: 12
  },
  {
    key: "emergency",
    name: "Emergency",
    type: "special-pennant",
    category: "special",
    meaning: "Signal(s) Flying Are to be Obeyed as Soon as Understood.",
    description: "Checkered red and white.",
    phonetic: "E-mer-gen-see",
    tips: "Red and white checkers imply danger/emergency.",
    colors: ["red", "white"],
    pattern: "checkered",
    imagePath: "/flags/special-pennants/emergency.svg",
    difficulty: "beginner",
    order: 5
  },
  {
    key: "flotilla",
    name: "Flotilla",
    type: "special-pennant",
    category: "special",
    meaning: "Flotilla.",
    description: "Flotilla pennant.",
    phonetic: "Flo-til-la",
    tips: "Flotilla indicator.",
    colors: ["black", "white"],
    pattern: "misc",
    imagePath: "/flags/special-pennants/flotilla.svg",
    difficulty: "advanced",
    order: 24
  },
  {
    key: "formation",
    name: "Formation",
    type: "special-pennant",
    category: "special",
    meaning: "Formation.",
    description: "Pennant with red and white horizontal bands.",
    phonetic: "For-ma-tion",
    tips: "Red and white horizontal.",
    colors: ["red", "white"],
    pattern: "horizontal-bicolor",
    imagePath: "/flags/special-pennants/formation.svg",
    difficulty: "advanced",
    order: 13
  },
  {
    key: "interrogative",
    name: "Interrogative",
    type: "special-pennant",
    category: "special",
    meaning: "Signal Not Understood (Question).",
    description: "Pennant pointed at end (or burgee shape) depending on usage.",
    phonetic: "In-ter-rog-a-tive",
    tips: "Often red/white vertical stripes or specialized shape.",
    colors: ["red", "white"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/interrogative.svg",
    difficulty: "intermediate",
    order: 6
  },
  {
    key: "negat",
    name: "Negat",
    type: "special-pennant",
    category: "special",
    meaning: "Negative.",
    description: "Checkered yellow and red.",
    phonetic: "Neg-at",
    tips: "Negative answer.",
    colors: ["yellow", "red"],
    pattern: "checkered",
    imagePath: "/flags/special-pennants/negat.svg",
    difficulty: "intermediate",
    order: 7
  },
  {
    key: "port",
    name: "Port",
    type: "special-pennant",
    category: "special",
    meaning: "Out of Routine / Turn to Port.",
    description: "Pennant with red and white vertical stripes.",
    phonetic: "Port",
    tips: "Red for Port (left).",
    colors: ["red", "white"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/port.svg",
    difficulty: "advanced",
    order: 11
  },
  {
    key: "prep",
    name: "Prep",
    type: "special-pennant",
    category: "special",
    meaning: "Preparative.",
    description: "Yellow with green horizontal stripe.",
    phonetic: "Prep",
    tips: "Prepare for signal.",
    colors: ["yellow", "green"],
    pattern: "horizontal-stripes",
    imagePath: "/flags/special-pennants/prepare.svg",
    difficulty: "intermediate",
    order: 8
  },
  {
    key: "screen",
    name: "Screen",
    type: "special-pennant",
    category: "special",
    meaning: "Screen.",
    description: "Black and white?",
    phonetic: "Screen",
    tips: "Screening formation.",
    colors: ["black", "white"],
    pattern: "misc",
    imagePath: "/flags/special-pennants/screen.svg",
    difficulty: "advanced",
    order: 15
  },
  {
    key: "speed",
    name: "Speed",
    type: "special-pennant",
    category: "special",
    meaning: "Speed.",
    description: "Red pennant with white/blue?",
    phonetic: "Speed",
    tips: "Indicates speed change.",
    colors: ["red", "white"],
    pattern: "misc",
    imagePath: "/flags/special-pennants/speed.svg",
    difficulty: "advanced",
    order: 16
  },
  {
    key: "squad",
    name: "Squad",
    type: "special-pennant",
    category: "special",
    meaning: "Squadron.",
    description: "Pennant with yellow and black vertical stripes.",
    phonetic: "Squad",
    tips: "Squadron indicator.",
    colors: ["black", "yellow"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/squadron.svg",
    difficulty: "advanced",
    order: 9
  },
  {
    key: "starboard",
    name: "Starboard",
    type: "special-pennant",
    category: "special",
    meaning: "Indefinite Turn to Starboard / National Flag.",
    description: "Pennant with green and white vertical stripes.",
    phonetic: "Star-bord",
    tips: "Green for Starboard (right).",
    colors: ["green", "white"],
    pattern: "vertical-stripes",
    imagePath: "/flags/special-pennants/starboard.svg",
    difficulty: "advanced",
    order: 10
  },
  {
    key: "station",
    name: "Station",
    type: "special-pennant",
    category: "special",
    meaning: "Station.",
    description: "Red pennant?",
    phonetic: "Stay-shun",
    tips: "Take station.",
    colors: ["red"],
    pattern: "solid",
    imagePath: "/flags/special-pennants/station.svg",
    difficulty: "advanced",
    order: 17
  },
  {
    key: "subdivision",
    name: "Subdivision",
    type: "special-pennant",
    category: "special",
    meaning: "Subdivision.",
    description: "Pennant.",
    phonetic: "Sub-di-vi-sion",
    tips: "Subdivision indicator.",
    colors: ["blue", "white"],
    pattern: "misc",
    imagePath: "/flags/special-pennants/subdivision.svg",
    difficulty: "advanced",
    order: 18
  },
  {
    key: "turn",
    name: "Turn",
    type: "special-pennant",
    category: "special",
    meaning: "Turn.",
    description: "Pennant.",
    phonetic: "Turn",
    tips: "Commence turn.",
    colors: ["white", "black"],
    pattern: "misc",
    imagePath: "/flags/special-pennants/turn.svg",
    difficulty: "advanced",
    order: 19
  }
];

export const SUBSTITUTES: Omit<Doc<"flags">, "_id" | "_creationTime">[] = [
  {
    key: "sub1",
    name: "1st Substitute",
    type: "substitute",
    category: "special",
    meaning: "Substitute for the first flag in this hoist.",
    description: "Yellow triangle with blue border.",
    phonetic: "First Sub",
    tips: "Yellow inside blue.",
    colors: ["yellow", "blue"],
    pattern: "border",
    imagePath: "/flags/substitutes/firstsub.svg",
    difficulty: "advanced",
    order: 20
  },
  {
    key: "sub2",
    name: "2nd Substitute",
    type: "substitute",
    category: "special",
    meaning: "Substitute for the second flag in this hoist.",
    description: "Blue and white halved triangle.",
    phonetic: "Second Sub",
    tips: "Blue/White halves.",
    colors: ["blue", "white"],
    pattern: "bicolor",
    imagePath: "/flags/substitutes/secondsub.svg",
    difficulty: "advanced",
    order: 21
  },
  {
    key: "sub3",
    name: "3rd Substitute",
    type: "substitute",
    category: "special",
    meaning: "Substitute for the third flag in this hoist.",
    description: "White with black horizontal stripe.",
    phonetic: "Third Sub",
    tips: "White with black stripe.",
    colors: ["white", "black"],
    pattern: "horizontal-stripes",
    imagePath: "/flags/substitutes/thirdsub.svg",
    difficulty: "advanced",
    order: 22
  },
  {
    key: "sub4",
    name: "4th Substitute",
    type: "substitute",
    category: "special",
    meaning: "Substitute for the fourth flag in this hoist.",
    description: "Red square with yellow square in center (or similar).",
    phonetic: "Fourth Sub",
    tips: "Red with yellow center.",
    colors: ["red", "yellow"],
    pattern: "misc",
    imagePath: "/flags/substitutes/foursub.svg",
    difficulty: "advanced",
    order: 23
  }
];